Template fixes
surfstudio/Xcode-Project-Templates pull request #39
Opened 2019-09-02 13:36 UTC by chausovSurfStudio

В данном ПРе поправлены следующие проблемы:

### Changes: ####
* структура нового проекта из этого шаблона заточена под архитектуру с координаторами
* файлы для CI теперь автоматом добавляются, не надо их потом тянуть извне
* и теперь на PR будут автоматом тесты гоняться, необходимый код для этого добавлен
* обновил fastfile, но тут я не шибко силен, надо обсуждать
* поправил опечатку в swiftlint yaml файле, из-за которой проект из коробки не собирался
* обновил версии для cocoapods и fastlane
* commit-msg хук поправил
* обновил слегка Makefile, там теперь help команда есть ) для таких забывчивых как я
* ну и расширение одно добавил в модуль с тестами, которое нужно для написание тестов на утечку памяти

#### Notes: ####
* не уверен, все ли из этого нужно в шаблон включать, может быть что-то планировалось как раз таки добавлять/изменять извне (к примеру, логику в fastfile или доп файлы для поддержания архитектуры с координаторами)
* и не уверен, стоило ли мне писать это сообщение на русском, может на английском тут надо?)
* а почему тут Вани

2019-09-02 13:51 UTC, ismetanin reviewed
@chausovSurfStudio 
> а почему тут Ваню Сметанина нельзя в ревьюеры добавить?(

Потому что я не в тиме уже 😢

Но если тебе важно, то ПР мне нравится, только ты ещё можешь убрать `.gitkeep` файл из тех директорий, где уже есть какие-то ещё файлы, `.gitkeep` нужен для того чтобы папка в гит закоммитилась, гит не умеет в пустые папки

И ещё как совет: какие-то спорные моменты можно будет закрыть под опции по типу как в стандартном шаблоне "Use Core Data" выглядит например

2019-09-02 13:51 UTC, ismetanin commented on Surf MVP Application.xctemplate/CoordinatorsSupport/BaseCoordinator.swift
> +    func start() {
MARK-а не хватает, кажется

2019-09-02 14:12 UTC, chausovSurfStudio commented
> @chausovSurfStudio
> 
> > а почему тут Ваню Сметанина нельзя в ревьюеры добавить?(
> 
> Потому что я не в тиме уже 😢
> 
> Но если тебе важно, то ПР мне нравится, только ты ещё можешь убрать `.gitkeep` файл из тех директорий, где уже есть какие-то ещё файлы, `.gitkeep` нужен для того чтобы папка в гит закоммитилась, гит не умеет в пустые папки
> 
> И ещё как совет: какие-то спорные моменты можно будет закрыть под опции по типу как в стандартном шаблоне "Use Core Data" выглядит например

да вот да, надо только разобраться, как это делать)) чтобы под опции закрыть, а то уже от Сани поступило предложение разделить его на два: чистое MVP серфовское и MVP на координаторах

2019-09-03 05:18 UTC, ismetanin commented
Вот [тут можно почитать.](https://github.com/NSBoilerplate/Xcode-Project-Templates/wiki/Creating-Xcode-4.x-Project-Templates#type)

Но это муторно всё будет, особенно если будет много опций

2019-09-03 08:05 UTC, chausovSurfStudio commented
в общем, еще немного допилил, из нового:

- теперь два шаблона устанавливаются, один на обычный MVP, второй на MVP с координаторами
- шаблон с обычным MVP юзает шаблоны из студийного репозиторий, в структуре проекта старая добрая папка User Stories и сразу затягивается протокол+реализация для ModuleTransitionable
- шаблон с координаторами имеет выбор storyboard vs xib, для сторибордов - используются шаблоны из студийного репозитория, для ксибов - из его форка в моем репозитории (немного прокачал по код-стайлу + добавил шаблон для координатора, а то его я тоже устал сам руками писать, пусть генерится). Почему? Потому что мне сейчас еще холивара по поводу новых шаблонов не хватало на месяц, кто хочет - пусть юзает студийные со сторибордом, кто не хочет - мои, кто не желает ни те, ни другие - может свои затянуть
- по красоте добавил папку Templates/ в гитигнор
- ну и замечание Вани насчет марка поправил

2019-09-15 07:57 UTC, LastSprint approved these changes

2019-09-29 13:57 UTC, chausovSurfStudio commented
а пока не смержили: по горячим следам поправил два бага)

- добавил файл Localizable.strings в таргет приложения, а то строки свфитгеном генерились, а значения не цеплялись
- и добавил на Static code analysis стратегию FAIL_WHEN_STAGE_ERROR

2019-10-11 13:25 UTC, gregoryvit requested changes

2019-10-11 13:25 UTC, gregoryvit commented on Surf Base Application.xctemplate/AppDelegate.swift
>  import UIKit
Может заголовки уберем?

2019-10-11 13:25 UTC, gregoryvit commented on Surf Base Application.xctemplate/Podfile
>  platform :ios, '10.0'
Здесь наверное уже 11 стоит указать?
```suggestion
platform :ios, '11.0'
```

2019-10-11 13:25 UTC, gregoryvit commented on Surf Base Application.xctemplate/ci/JenkinsfilePullRequestJob.groovy
> +}
Вот это лишнее

2019-10-11 13:25 UTC, gregoryvit commented on Surf MVP Application.xctemplate/Colors.swift
> +//
Давай тут тоже уберем заголовки?

2019-10-11 13:25 UTC, gregoryvit commented on Surf MVP Application.xctemplate/Makefile
>    		-sudo gem install bundler;\
Здесь нужно явно указывать версию, которую нужно установить
```suggestion
  		-sudo gem install bundler -v "1.17.3";\
```

2019-10-11 13:25 UTC, gregoryvit commented on Surf MVP and Coordinators Application.xctemplate/Colors.swift
> +//
Здесь аналогично, давай уберем

2019-10-11 13:25 UTC, gregoryvit commented on Surf MVP and Coordinators Application.xctemplate/Storyboard/Makefile
> +  		-sudo gem install bundler;\
Нужно версию бандлера проставлять явно
```suggestion
  		-sudo gem install bundler -v "1.17.3";\
```

2019-10-11 13:25 UTC, gregoryvit commented on Surf MVP and Coordinators Application.xctemplate/Xib/Makefile
> +  		-sudo gem install bundler;\
Аналогично предыдущим
```suggestion
  		-sudo gem install bundle -v "1.17.3"r;\
```

2019-10-13 07:43 UTC, chausovSurfStudio commented on Surf Base Application.xctemplate/ci/JenkinsfilePullRequestJob.groovy
> +}
а почему бы и нет) почему считаешь, что лишнее?
по нашим процессам сюда можно на make lint сразу и CPD подвязать, и скрипт...

2019-10-13 07:52 UTC, chausovSurfStudio commented
@gregoryvit все поправил кроме PR джоба, его бы обсудить
право зарезолвить остальное оставляю за тобой)

2019-11-07 11:07 UTC, gregoryvit commented
@chausovSurfStudio вроде pr джоб обсудили, можно смотреть финально?

2019-11-10 14:10 UTC, chausovSurfStudio commented on Surf Base Application.xctemplate/ci/JenkinsfilePullRequestJob.groovy
> +}
вот теперь поправил

2019-11-10 14:11 UTC, chausovSurfStudio commented
@gregoryvit только сейчас руки дошли, поправил PR job, можно смотреть)

2019-11-21 07:01 UTC, gregoryvit approved these changes

2019-11-21 07:02 UTC, merged